[package]
name = "serde-xdr"
version = "0.1.0"
authors = ["Sam Gomena <sgomena@tripwire.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
byteorder = "*"